document.getElementById('show-addmoney').addEventListener("click",function(){
    showdisplyByid('show-add-money')
})
document.getElementById('show-history').addEventListener("click",function(){
    showdisplyByid('show-history-tran')
})
document.getElementById('show-cashOut').addEventListener("click",function(){
    showdisplyByid('show-cash-out')
})